learning_rate: 1.0e-5
num_epochs: 2
lr_scheduler_type: "constant"
batch_size: 1
gradient_accumulation_steps: 4
weight_decay: 0.01
logging_steps: 0.1
save_steps: 2500
eval_steps: 0.1
eval_strategy: "steps"
bf16: false
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
report_to: "tensorboard"
